{{--
    The Store Settlement Statement.

    One template for both the screen and the PDF, so what is discussed on a
    laptop and what gets signed on paper cannot drift apart.

    Laid out in tables rather than flex or grid on purpose: dompdf renders this,
    and its support for modern layout is thin enough that a grid that looks
    right in a browser can collapse in the exported file — which nobody notices
    until the copy in somebody's hand is the wrong one.

    Every figure here comes from the frozen payload, never recomputed at render.
    A statement that recalculated itself on open would answer a different
    question each time it was looked at.
--}}
@php
    $p          = $statement->payload;
    $cash       = $p['cash'] ?? [];
    $out        = $p['outstanding'] ?? [];
    $profit     = $p['profit'] ?? [];
    $reversals  = $p['reversals'] ?? [];
    $stock      = $p['stock'] ?? ['counted' => false];
    $debt       = $out['unpaid_debt'] ?? ['total' => 0, 'buckets' => [], 'debtors' => []];
    // Sign before the symbol. number_format on a negative yields "₦-5,000.00",
    // which reads as a typo on a document somebody is about to sign.
    $money = function ($v) {
        $v = (float) $v;

        return ($v < 0 ? '-₦' : '₦') . number_format(abs($v), 2);
    };
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $statement->reference }} — {{ $statement->store->name }}</title>
    <style>
        @page { margin: 18mm 14mm; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #18181b; margin: 0; }
        h1 { font-size: 18px; margin: 0 0 2px; }
        /* page-break-after so a section heading never strands itself at the
           foot of a page with its figures overleaf. */
        h2 { font-size: 12px; text-transform: uppercase; letter-spacing: .06em; color: #71717a;
             margin: 22px 0 6px; border-bottom: 1px solid #e4e4e7; padding-bottom: 4px;
             page-break-after: avoid; }
        /* Applied only to the short summary tables, never the debtor list:
           forcing a long table to stay whole pushes a mostly-blank page. */
        table.keep { page-break-inside: avoid; }
        .sub { color: #52525b; font-size: 11px; margin: 0 0 2px; }
        .ref { font-family: DejaVu Sans Mono, monospace; color: #a1a1aa; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 5px 6px; text-align: left; vertical-align: top; }
        th { font-weight: 600; color: #52525b; border-bottom: 1px solid #e4e4e7; font-size: 10px;
             text-transform: uppercase; letter-spacing: .04em; }
        .num { text-align: right; font-family: DejaVu Sans Mono, monospace; white-space: nowrap; }
        .row td { border-bottom: 1px solid #f4f4f5; }
        .total td { border-top: 2px solid #18181b; font-weight: 700; }
        .headline { background: #fafafa; border: 1px solid #e4e4e7; padding: 10px 12px; margin-top: 8px; }
        .headline .label { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #71717a; }
        .headline .value { font-size: 22px; font-weight: 700; }
        .short { color: #b91c1c; }
        .clear { color: #15803d; }
        .muted { color: #71717a; }
        .warn { background: #fffbeb; border: 1px solid #fde68a; padding: 8px 10px; margin-top: 6px; }
        .sign { margin-top: 10px; border: 1px solid #e4e4e7; }
        .sign td { height: 46px; border: 1px solid #e4e4e7; }
    </style>
</head>
<body>

    <h1>Store Settlement Statement</h1>
    <p class="sub">
        <strong>{{ $statement->store->name }}</strong> ·
        {{ $statement->period_start->format('d M Y') }} to {{ $statement->period_end->format('d M Y') }}
    </p>
    <p class="ref">
        {{ $statement->reference }} · generated by {{ $statement->generatedBy->name }}
        on {{ $statement->generated_at->format('d M Y, g:ia') }}
    </p>

    {{-- The number the settlement conversation is actually about, given its own
         box so nobody has to hunt for it among figures that merely support it. --}}
    <div class="headline">
        <div class="label">Unexplained shortage</div>
        <div class="value {{ (float) ($out['true_shortage'] ?? 0) > 0.009 ? 'short' : 'clear' }}">
            {{ $money($out['true_shortage'] ?? 0) }}
        </div>
        <div class="muted">
            @if ((float) ($out['true_shortage'] ?? 0) > 0.009)
                Everything else below is accounted for. This is what is not.
            @else
                Every naira is accounted for by the buckets below.
            @endif
        </div>
    </div>

    <h2>Trading</h2>
    <table>
        <tr class="row"><td>Revenue</td><td class="num">{{ $money($profit['revenue'] ?? 0) }}</td></tr>
        <tr class="row"><td>Cost of goods sold</td><td class="num">({{ $money($profit['cogs'] ?? 0) }})</td></tr>
        <tr class="total"><td>Profit</td><td class="num">{{ $money($profit['profit'] ?? 0) }}</td></tr>
    </table>
    <p class="muted" style="margin-top:6px">
        Profit counts every sale, however it was paid for. The cash below counts only the cash tender.
    </p>

    <h2>Cash</h2>
    <table>
        <tr class="row"><td>Cash collected</td><td class="num">{{ $money($cash['takings'] ?? 0) }}</td></tr>
        <tr class="row"><td>Spent from the cash</td><td class="num">({{ $money($cash['till_expenses'] ?? 0) }})</td></tr>
        <tr class="total"><td>Should be handed over</td><td class="num">{{ $money($cash['expected'] ?? 0) }}</td></tr>
        <tr class="row"><td>Handed over and confirmed</td><td class="num">{{ $money($cash['confirmed'] ?? 0) }}</td></tr>
        <tr class="total">
            <td>Difference</td>
            <td class="num {{ (float) ($cash['shortage'] ?? 0) > 0.009 ? 'short' : '' }}">{{ $money($cash['shortage'] ?? 0) }}</td>
        </tr>
    </table>

    <h2>Where the difference sits</h2>
    <table>
        <tr class="row">
            <td>Owed by customers (not cash yet)</td>
            <td class="num">{{ $money($debt['total'] ?? 0) }}</td>
        </tr>
        <tr class="row">
            <td>Taken but not handed over</td>
            <td class="num">{{ $money($out['unsubmitted'] ?? 0) }}</td>
        </tr>
        <tr class="row">
            <td>Handed over, awaiting confirmation</td>
            <td class="num">{{ $money($out['pending_confirmation'] ?? 0) }}</td>
        </tr>
        <tr class="row">
            <td>Disputed — two people disagree</td>
            <td class="num">{{ $money($out['disputed'] ?? 0) }}</td>
        </tr>
        <tr class="total">
            <td>Unexplained shortage</td>
            <td class="num {{ (float) ($out['true_shortage'] ?? 0) > 0.009 ? 'short' : '' }}">
                {{ $money($out['true_shortage'] ?? 0) }}
            </td>
        </tr>
        @if ((float) ($out['overage'] ?? 0) > 0.009)
            <tr class="row">
                <td>Overage — more handed over than the tills took</td>
                <td class="num">{{ $money($out['overage']) }}</td>
            </tr>
        @endif
    </table>

    @if (! empty($p['position']))
        @php $pos = $p['position']; @endphp
        <h2>Where the money is tied up</h2>
        <table class="keep">
            <tr class="row">
                <td>Stock on hand <span class="muted">(at cost, {{ number_format($pos['stock_units'] ?? 0) }} units)</span></td>
                <td class="num">{{ $money($pos['stock_at_cost'] ?? 0) }}</td>
            </tr>
            <tr class="row"><td>Cash still to be handed over</td><td class="num">{{ $money($pos['cash_outstanding'] ?? 0) }}</td></tr>
            <tr class="row"><td>Owed by customers</td><td class="num">{{ $money($pos['customer_debt'] ?? 0) }}</td></tr>
            <tr class="row">
                {{-- Labelled, never silently mixed: this one line is at selling
                     price while every other is at cost. --}}
                <td>Pickings out on trust <span class="muted">(at selling price)</span></td>
                <td class="num">{{ $money($pos['pickings_retail'] ?? 0) }}</td>
            </tr>
            <tr class="row"><td>Owed by staff</td><td class="num">{{ $money($pos['staff_debts'] ?? 0) }}</td></tr>
            <tr class="total"><td>Total balance</td><td class="num">{{ $money($pos['total_balance'] ?? 0) }}</td></tr>
        </table>

        @if (($pos['stock_uncosted'] ?? 0) > 0)
            <div class="warn">
                {{ $pos['stock_uncosted'] }} product(s) on the shelf have no cost price recorded and are left out of the
                stock value above, so the total is understated.
            </div>
        @endif

        <h2>Trading in this period</h2>
        <table class="keep">
            <tr class="row"><td>Total sold</td><td class="num">{{ $money($pos['sold_in_range'] ?? 0) }}</td></tr>
            <tr class="row"><td>Cost of what sold</td><td class="num">({{ $money($pos['cogs_in_range'] ?? 0) }})</td></tr>
            <tr class="row"><td>Stock purchased</td><td class="num">{{ $money($pos['purchases'] ?? 0) }}</td></tr>
            <tr class="row"><td>Expenses</td><td class="num">{{ $money($pos['expenses'] ?? 0) }}</td></tr>
            <tr class="total"><td>Gross profit</td><td class="num">{{ $money($pos['profit_in_range'] ?? 0) }}</td></tr>
        </table>
        <p class="muted" style="margin-top:6px">
            Gross profit is what sold less what it cost. Stock purchased and expenses sit beside it but are not taken
            off it — buying stock moves money onto the shelf, it does not lose it.
        </p>
    @endif

    <h2>Who collected it</h2>
    @if (! empty($p['cashiers']))
        <table>
            <tr>
                <th>Cashier</th>
                <th class="num">Cash collected</th>
                <th class="num">Handed over</th>
                <th class="num">Still to hand over</th>
            </tr>
            @foreach ($p['cashiers'] as $c)
                <tr class="row">
                    <td>{{ $c['name'] }}</td>
                    <td class="num">{{ $money($c['collected']) }}</td>
                    <td class="num">{{ $money($c['handed_over']) }}</td>
                    <td class="num {{ (float) $c['outstanding'] > 0.009 ? 'short' : '' }}">{{ $money($c['outstanding']) }}</td>
                </tr>
            @endforeach
        </table>
    @elseif (array_key_exists('cashiers', $p))
        <p class="muted">Nobody collected cash at this branch in this period.</p>
    @else
        {{-- Frozen before this statement recorded who collected what. Saying so
             beats "nobody collected cash", which would be a claim about the
             period rather than about the record. --}}
        <p class="muted">Not recorded on this statement.</p>
    @endif

    <h2>Stock</h2>
    @if ($stock['counted'] ?? false)
        @php
            $v = $stock['variance'] ?? [];
            $rows = $stock['discrepancies'] ?? [];
            $missingAtSelling = (float) ($v['missing_at_selling'] ?? 0);
        @endphp
        <p class="muted" style="margin:0 0 6px">
            Counted{{ ($stock['counted_by'] ?? null) ? ' by ' . $stock['counted_by'] : '' }}
            on {{ $stock['counted_at'] ?? '—' }}.
        </p>

        @if ($rows === [])
            <p class="muted">Everything counted matched the books.</p>
        @else
            <table class="{{ count($rows) <= 12 ? 'keep' : '' }}">
                <tr>
                    <th>Product</th>
                    <th class="num">Should be</th>
                    <th class="num">Counted</th>
                    <th class="num">Missing</th>
                    <th class="num">At selling price</th>
                </tr>
                @foreach ($rows as $row)
                    <tr class="row">
                        <td>{{ $row['product'] }}</td>
                        <td class="num">{{ $row['system'] }}</td>
                        <td class="num">{{ $row['counted'] }}</td>
                        <td class="num {{ $row['missing'] > 0 ? 'short' : '' }}">
                            {{ $row['missing'] > 0 ? $row['missing'] : '+' . abs($row['missing']) }}
                        </td>
                        <td class="num">{{ $row['missing'] > 0 ? $money($row['at_selling']) : '—' }}</td>
                    </tr>
                @endforeach
                <tr class="total">
                    <td colspan="3">Missing stock, at selling price</td>
                    <td class="num">{{ $v['units'] ?? 0 }}</td>
                    <td class="num {{ $missingAtSelling > 0.009 ? 'short' : '' }}">{{ $money($missingAtSelling) }}</td>
                </tr>
            </table>

            {{-- The two signals put together, in words, because this is the copy
                 somebody signs and they should not have to infer it. --}}
            <p class="muted" style="margin-top:6px">
                @php $cashShort = (float) ($out['true_shortage'] ?? 0); @endphp
                @if ($missingAtSelling > 0.009 && $cashShort > 0.009)
                    Both stock and cash are short. Goods left and the money for them did not arrive.
                @elseif ($missingAtSelling > 0.009)
                    Stock is short while the cash balances — goods left without a sale being rung up.
                @elseif ($cashShort > 0.009)
                    Cash is short while the stock is right — the goods sold properly and the money went missing after.
                @endif
            </p>
        @endif
    @else
        {{-- Said outright rather than left blank: a settlement with no count
             behind it has only checked the money, and goods that left without
             ever being rung would not appear anywhere above. --}}
        <div class="warn">
            No physical count was entered for this period. The cash figures above cannot
            see goods that left without being rung up.
        </div>
    @endif

    <h2>Sales withdrawn in this period</h2>
    @if (($reversals['count'] ?? 0) > 0)
        <table>
            <tr class="row"><td>Sales voided or returned</td><td class="num">{{ $reversals['count'] }}</td></tr>
            <tr class="row">
                <td>Of those, cash sales voided</td>
                <td class="num">{{ $reversals['voided_cash_count'] ?? 0 }} · {{ $money($reversals['voided_cash'] ?? 0) }}</td>
            </tr>
        </table>
        @if (($reversals['unexplained'] ?? 0) > 0)
            {{-- A void removes money from expected cash after the fact, so one
                 with no stated reason is exactly the shape of a covered theft. --}}
            <div class="warn">
                {{ $reversals['unexplained'] }} of these were voided with no reason given.
            </div>
        @endif
    @else
        <p class="muted">None.</p>
    @endif

    <h2>Debtors</h2>
    @if (($debt['total'] ?? 0) > 0.009)
        @php $b = $debt['buckets'] ?? []; @endphp
        <table>
            <tr>
                <th>Up to 7 days</th><th>8–30 days</th><th>31–60 days</th><th>Over 60 days</th>
            </tr>
            <tr class="row">
                <td class="num">{{ $money($b['current'] ?? 0) }}</td>
                <td class="num">{{ $money($b['8_30'] ?? 0) }}</td>
                <td class="num">{{ $money($b['31_60'] ?? 0) }}</td>
                <td class="num">{{ $money($b['over_60'] ?? 0) }}</td>
            </tr>
        </table>
        @if (! empty($debt['debtors']))
            <table style="margin-top:8px">
                <tr><th>Customer</th><th>Owing since</th><th class="num">Outstanding</th></tr>
                @foreach (array_slice($debt['debtors'], 0, 25) as $d)
                    <tr class="row">
                        <td>{{ $names[$d['customer_id']] ?? ('Customer #' . $d['customer_id']) }}</td>
                        <td>{{ $d['days_oldest'] }} days</td>
                        <td class="num">{{ $money($d['outstanding']) }}</td>
                    </tr>
                @endforeach
            </table>
        @endif
    @else
        <p class="muted">Nothing outstanding.</p>
    @endif

    @if ($statement->resolutions->isNotEmpty())
        <h2>What was agreed</h2>
        <table>
            <tr><th>Concerns</th><th>Outcome</th><th class="num">Amount</th><th>Note</th></tr>
            @foreach ($statement->resolutions as $r)
                <tr class="row">
                    <td>{{ str_replace('_', ' ', (string) $r->concerns) }}</td>
                    <td>{{ str_replace('_', ' ', $r->outcome) }}</td>
                    <td class="num">{{ $r->amount !== null ? $money($r->amount) : '—' }}</td>
                    <td>{{ $r->note }}</td>
                </tr>
            @endforeach
        </table>
    @endif

    <h2>Signoff</h2>
    <table class="sign">
        <tr>
            <td width="50%"><span class="muted">Storekeeper — name &amp; signature</span></td>
            <td width="50%"><span class="muted">Received by — name &amp; signature</span></td>
        </tr>
        <tr>
            <td><span class="muted">Date</span></td>
            <td><span class="muted">Date</span></td>
        </tr>
    </table>

    <p class="ref" style="margin-top:14px">
        Figures frozen at {{ $statement->generated_at->format('d M Y, g:ia') }}. Later corrections
        do not change this copy — run a fresh statement to see where things now stand.
    </p>

</body>
</html>
